name: Action Push to master
on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Action push"]
    types: [completed]
jobs:
  Success:
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "Success!!!!"
