name: CI
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Installing dependencies
        run: |
          sudo apt-get -y install pulseaudio libpulse-dev gcc meson ninja-build tdb-tools libtdb-dev libsndfile-dev check doxygen libavahi-client-dev
      - name: Clonning pulseaudio repository
        run: git clone https://gitlab.freedesktop.org/pulseaudio/pulseaudio.git
      - name: Configuring Pulseaudio (meson)
        run: meson build pulseaudio
      - name: Configuring Pulseaudio (ninja)
        run: ninja -C build
      - name: Copying config.h
        run: cp ./build/config.h ./src/
      - name: Compiling
        run: gcc -g -shared  -fPIC -I $PWD/pulseaudio/src -o module-airplay-discover.so ./src/module-airplay-discover.c
      - name: Creating artifact
        uses: actions/upload-artifact@v2
        with:
          name: module-airplay-so
          path: |
            module-airplay-discover.so
  Success:
    needs: Build
    if: ${{ needs.Build.result == 'success' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "Success!!!!"
